# Generated by Django 3.2.2 on 2021-05-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0002_rename_employee_userregisteration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegisteration',
            new_name='UserRegistration',
        ),
    ]
