# Generated by Django 3.2.2 on 2021-05-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0004_addproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='file_category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Books', 'Books')], max_length=50),
        ),
    ]
