# Generated by Django 3.2.2 on 2021-05-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0005_alter_addproduct_file_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addproduct',
            new_name='addproducts',
        ),
        migrations.AlterModelTable(
            name='addproducts',
            table='addproducts',
        ),
    ]
