# Generated by Django 3.2.2 on 2021-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0006_auto_20210515_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('file_category', models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Books', 'Books')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('attachment', models.FileField(upload_to='')),
                ('description', models.TextField(max_length=255)),
                ('fileuploadtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'addproduct1',
            },
        ),
        migrations.DeleteModel(
            name='addproducts',
        ),
    ]
