# Generated by Django 3.2.2 on 2021-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0008_auto_20210515_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='attachment',
            field=models.ImageField(upload_to=''),
        ),
    ]
