# Generated by Django 3.2.2 on 2021-05-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0009_alter_additem_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='attachment',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
