# Generated by Django 3.2.2 on 2021-05-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0011_alter_additem_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='file_category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Books', 'Books')], max_length=50),
        ),
    ]
