# Generated by Django 3.2.2 on 2021-05-17 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysql_app', '0012_alter_additem_file_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('attachment', models.ImageField(upload_to='cartimages/')),
                ('fileuploadtime', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'cartpage',
            },
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user',
            field=models.OneToOneField(default='KLU123', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
