# Generated by Django 3.2.2 on 2021-05-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0014_alter_userregistration_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartpage',
        ),
    ]
