# Generated by Django 3.2.2 on 2021-05-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0015_delete_cartpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='user',
        ),
    ]
