# Generated by Django 3.2.2 on 2021-05-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0016_remove_userregistration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('attachment', models.ImageField(upload_to='cartimages/')),
                ('fileuploadtime', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'cartpage',
            },
        ),
    ]
