# Generated by Django 3.2.2 on 2021-05-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0017_cartpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartpage',
            new_name='cartpage1',
        ),
        migrations.AlterModelTable(
            name='cartpage1',
            table='cartpage1',
        ),
    ]
