# Generated by Django 3.2.2 on 2021-05-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_app', '0020_userregistration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='user',
        ),
    ]
